In [1]:
import numpy as np

In [2]:
A= np.array([[1,3],[4,5]])
A

array([[1, 3],
       [4, 5]])

In [4]:
Ainv = np.linalg.inv(A)
Ainv

array([[-0.71428571,  0.42857143],
       [ 0.57142857, -0.14285714]])

In [5]:
b = np.array([5,33])
b

array([ 5, 33])

In [6]:
x = np.dot(Ainv,b)
x

array([10.57142857, -1.85714286])

In [7]:
np.dot(A,x)

array([ 5., 33.])