In [ ]:
import numpy as np

In [4]:
import numpy as np
a = np.array([1,3,3])
b = np.array([1,3,5])
c = np.array([1,3,3,5])
print(a+b)
print (a-c) # will cause an error 

[2 6 8]


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [5]:
print(a*b)

[ 1  9 15]


In [6]:
a/b

array([1. , 1. , 0.6])